/*
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        char a='\0';
        string res = s+t;
        for(int i=0;i<res.length();i++){
            a^=res[i];
        }
        return a;
    }
};
